### ISSUE TITLE
Import statement is removed when another variable is added

### ISSUE THREAD

**Issue by trotzig** [dabbott/vscode-import-js#6] opened 2017-11-27 09:42 UTC
👋 

This is a carry-over from an issue reported in the upstream import-js project: 
https://github.com/Galooshi/import-js/issues/467

If I have a file with an existing import statement

```js
import { foo } from './foobar';

foo();
bar();
```

then if I try to import `bar`, which is a named export of the `./foobar.js` file, I get this: 

```js

foo();
bar();
```

Other plugins (e.g. vim, sublime) correctly combines the two variables in one statement: 

```js
import { bar, foo } from './foobar';

foo();
bar();
```

**Comment by feifanzhou** [comment] 2018-04-04 21:50
@trotzig @dabbott would you guys be able to fix this issue? I love this extension in Sublime, but it's a blocker for VSCode.

**Comment by trotzig** [comment] 2018-04-06 15:07
I personally don’t use vscode myself, but I’d be happy to review anything that you can come up with to fix this.

**Comment by dabbott** [comment] 2018-04-06 23:06
@feifanzhou I'm also happy to review anything if you wanna make a fix. Since vscode supports importing JS deps out of the box now, I haven't been using this plugin much 😱

**Comment by feifanzhou** [comment] 2018-04-06 23:08
@dabbott Oh whoa it does? How do I use VSCode's built-in import?

**Comment by dabbott** [comment] 2018-04-06 23:24
I don't think I had to do anything to enable it. When you start typing the name of the component, it'll suggest names from packages. When you choose an autocomplete suggestion, it'll import the package if needed.

There are definitely still use cases that VSCode doesn't support though and that ImportJS does 😄
but I haven't been writing much JS these days.

**Comment by feifanzhou** [comment] 2018-04-07 22:07
Yeah, working on a Flow-based project, most symbols don't seem to show up in autocomplete unfortunately. I'm happy to try a fix for this issue … any tips on where to start? (I haven't worked with VSCode extensions before)

**Comment by dabbott** [comment] 2018-04-08 00:50
@feifanzhou this was my first time working on a VSCode extension. I found it pretty easy. I probably should've used typescript for nicer autocomplete so I didn't have to look up docs.

Anyway, I suspect it has something to do with this: I do a diff of the current file https://github.com/dabbott/vscode-import-js/blob/master/lib/project.js#L37 based on the implementation Atom uses internally https://github.com/dabbott/vscode-import-js/blob/master/lib/textEditsForDiff.js (since VSCode didn't have an API for that at the time -- and maybe still doesn't). I'm likely just doing a bad diff.

I'd start in the `syncFileContents` function and console.log the `newText` argument. In the upstream issue it sounded like the problem is specific to VSCode, so presumably `syncFileContents` is called with the correct text, but that's probably the first thing I'd check.

**Comment by feifanzhou** [comment] 2018-04-08 17:11
@dabbott got it! Can you review, merge, and release?

**Closed as completed** 2018-04-09 16:18 UTC

**Comment by dabbott** [comment] 2018-04-09 16:24
@feifanzhou released! Let me know if it didn't work for some reason

**Comment by feifanzhou** [comment] 2018-04-09 16:28
Looks like it’s working great — thanks!
